spring-financial-group/terraform-jx-azure

values.auto.tfvars

This is to cope with case service builds having an increase ram necessity

feat: move build nodes to 32GB EPYC machines

---

cluster/jx-requirements.yml.tpl
cluster/requirements.tf
cluster/terraform-jx-cluster-aks/cluster/outputs.tf
cluster/terraform-jx-cluster-aks/outputs.tf

add the cluster nodes resource group client id to jx-requirements so that we can pull it into build-scan-push

feat: add client_id to jx-requirements

---

cluster/main.tf
cluster/terraform-jx-azure-storage/main.tf
cluster/terraform-jx-azuredns/main.tf
cluster/terraform-jx-azurekeyvault/main.tf
cluster/terraform-jx-boot/boot.tf
cluster/terraform-jx-cluster-aks/cluster/logging.tf
cluster/terraform-jx-cluster-aks/cluster/main.tf
cluster/terraform-jx-cluster-aks/cluster/outputs.tf
cluster/terraform-jx-cluster-aks/cluster/variables.tf
cluster/terraform-jx-cluster-aks/main.tf
cluster/terraform-jx-cluster-aks/outputs.tf
cluster/terraform-jx-cluster-aks/variables.tf
cluster/terraform-jx-registry-acr-oss/main.tf
cluster/terraform-jx-registry-acr/main.tf
main.tf
values.auto.tfvars
variables.tf

k8s 1.27.3 and AzureRM 3.0.0 UPGRADE:
NOTE: Due to the k8s 1.27.3 and Azurerm 3.0.0 + there is drift and new behaviour with the many AKS resources.
Changes in this PR:
- upgrade to latest azurerm version
- terraform init --upgrade applied which has upgraded all version and kept up to date with remote workspace
- microsoft defender resource group and log analytics workspace now managed and associated with the cluster
- SKU Tier changed from ' Paid ' to ' Standard '
- changes in AKS cluster for current config due to addon profile being deprecated:
```
role_based_access_control {
enabled = true
azure_active_directory {
managed = true
}
}
addon_profile {
dynamic "oms_agent" {
for_each = var.enable_log_analytics ? [""] : []
content {
enabled                    = var.enable_log_analytics …
```

chore: upgrade to latest azurerm version

---

cluster/terraform-jx-boot/vault.tf
values.auto.tfvars

- We currently are at max ml-nodes (5).
-  due to jx-nbs we need another ml-node as services are not spinning up
- increase max node count to 6

fix: increase max ml node to 6

---

cluster/local.tf
cluster/main.tf
cluster/terraform-jx-azurekeyvault/outputs.tf
cluster/terraform-jx-azurekeyvault/variables.tf

Adds `AZURE_CLIENT_ID` to the secret `jx-boot-job-env-vars`. This allows use to specify the identity used when attempting to authenticate with azure from the cluster.
Follows from issues with multiple identities existing when trying to populate secrets from initial bootjob.
Relevant PR in jx-land https://github.com/jenkins-x-plugins/secretfacade/pull/20

feat: add kubelet client ID to bootjob env vars

---

cluster/outputs.tf
output.tf

- this helps by using the module as a data source within the same terraform workspace to pass values into other resources. E.g granting access to mqube-build acr 
- Could hardcode these values, but better to utilise the state file incase of any changes

feat: bring forward outputs to use in other modules

---

cluster/terraform-jx-registry-acr/main.tf

Removing the repo namespace to see if it starts caching properly

chore: only wildcard to check if working

---

values.auto.tfvars

Got two ml build nodes kicking about with nothing on them. May as well reduce to 0 as we're not using them currently.

fix: reduce min ml build node count 2 -> 0

---

cluster/terraform-jx-cluster-aks/cluster/main.tf

- add conditional logic to the auto upgrade blocks and fix the issues that persisted with the upgrade 
- with new azurerm provider the node os channel will default to ```NodeImage``` change this to ```None```

fix: auto upgrades with conditional logic

---

cluster/terraform-jx-cluster-aks/cluster/main.tf

- ideally ignore_changes would benefit auto_upgrades. But due to our process of manual upgrades, the ignore_changes was blocking the node_pool upgrades. Best way to manage this, as there maybe drift in the versions is the correct population of the orch version and cluster version.

test: versions

---

values.auto.tfvars

Most our infra is HA w/3 replicas. Makes sense for use to have 3 separate nodes then each replica can be put on a different node.

chore: increase infra min node count -> 3

---

values.auto.tfvars

- Build/Infra/Default
- Move to Standard_D8s_v6/D4s
- Latest equivilant of what we're already using
- Similar price per cpu/ram
- ML (haven't changed but should)
- Move to Standard_NV4as_v4
- **Much** smaller than our current nodes but large enough to handle the workload
- Currently prod node requests 2.3 cpu & 8.4gb
- New node has 4 cpu & 14gb ram
- Old had 24 cpu & 448gb ram (not sure why we ever needed this much 🤷)
- Need to confirm with Rafay that AMD gpus are okay over NVIDIA Teslas
- @Reton2 says we need NVIDIA (gpt recommends Standard_NC6s_v3)

feat: update vm types

---

cluster/terraform-jx-cluster-aks/cluster/main.tf

- remove k8s automatic versioning. This was a fix to better manage patch versions, however, our control plane has version mismatch compared with the node pools which could be having an impact on state management.

fix: remove auto upgrade due to version mismatch

---

cluster/terraform-jx-cluster-aks/cluster/main.tf

- unfortunately this setting was missed when removing the schedule so its updated control plane again. 
- I will amend this weekend to make sure versions are aligned (but this wasn't the problem anyway)

fix: remove auto patch properly

---

cluster/main.tf
cluster/terraform-jx-azure-storage/main.tf
cluster/terraform-jx-azuredns/main.tf
cluster/terraform-jx-azurekeyvault/main.tf
cluster/terraform-jx-cluster-aks/cluster/main.tf
cluster/terraform-jx-cluster-aks/main.tf
cluster/terraform-jx-registry-acr-oss/main.tf
cluster/terraform-jx-registry-acr/main.tf

- upgrade azure version to keep in line with newest versions
- add a temporary node pool for when we are comfortable with updating in the future. This wasn't available on the previous az version

fix: upgrade az versions and add temp pools for future vm size upgrades

---

values.auto.tfvars

- Standard_D8s_v5 has been tested on our default node pool and stability has been brought back to our lovely cluster.
- Upgrading build and infra nodes to same vm size and version

feat: upgrade build and infra node pools

---

cluster/terraform-jx-cluster-aks/local.tf
cluster/terraform-jx-cluster-aks/main.tf

- unfortunately, even though the original conditional logic worked with NBS. It does not with monbs.
- Here I have amended the conditional and count logic on the resources.
- With the use of a toggle, when set to true, it will go ahead and create the resource and pass in the correct log_id and resource name from either the data object (terraform-jx azure instance) OR the resource object (SaaS instance).
- If set to false, it continues to use the data object
This has been tested on terraform-nbs and doesn't make any changes. And no changes in this pr.

feat: amend logic for defender resources

---

cluster/terraform-jx-cluster-aks/cluster/main.tf

- add new node label to the infra node pools. This will aid k8s vm size upgrades due to this label being added to the temp node pool.
- We currently define the nodeSelector as the agent pool, which is the name of the node. When running upgrades services dependent on this node pool can not migrate to the temp node pool

feat: add new node label to infra nodes

---

cluster/terraform-jx-registry-acr/main.tf

bitnami helm charts are _not_ being cached via ACR currently as they are not stored via `docker.io/*`
Instead, they use `registry-1.docker-io/*`, meaning the pullthrough rule is ignored, and the chart OCI artifacts are rate-limited by docker hub.
This change adds an explicit cache rule for `registry-1.docker-io/*`

feat: deploy new ACR cache rule for registry-1.docker-io/*

---

cluster/terraform-jx-registry-acr/main.tf

Revert change as ACR pull-through caching only applies to "public" docker repos

revert: acr bitnami cache rule
