- .gitignore
- cluster/main.tf
- cluster/terraform-jx-cluster-aks/cluster/main.tf
- cluster/terraform-jx-cluster-aks/cluster/variables.tf
- cluster/terraform-jx-cluster-aks/main.tf
- cluster/terraform-jx-cluster-aks/variables.tf
- cluster/variables.tf
- main.tf
- values.auto.tfvars
- variables.tf
- Created new node pool for priority services/pods
> New node pool

- cluster/terraform-jx-registry-acr/main.tf
- change to azurerm_resource_group.acr.name to specifically check if name is null
> feat: specifically check acr.name

- cluster/terraform-jx-registry-acr/main.tf
changing the value to "" to look for no string in name
> chore: change same type value to true

- cluster/terraform-jx-registry-acr/main.tf
this may not work - but other attempts have failed
> feat: test rg_name

- values.auto.tfvars
- spot node false to destroy and re-create on new k8s versionj
> feat: remove spot for k8s upgrade

- cluster/main.tf
- cluster/terraform-jx-cluster-aks/cluster/main.tf
- cluster/terraform-jx-cluster-aks/cluster/variables.tf
- cluster/terraform-jx-cluster-aks/main.tf
- cluster/terraform-jx-cluster-aks/variables.tf
- cluster/variables.tf
- main.tf
- values.auto.tfvars
- variables.tf
- prod cluster has azure policy enabled therefore added a new variable to auto.tfvars
> chore: add azure policy var

- cluster/terraform-jx-boot/main.tf
- cluster/terraform-jx-boot/vault.tf
- cluster/terraform-jx-cluster-aks/cluster/main.tf
- main.tf
- set values of the pvc size to 2Gi. This change can be managed in the future if error occurs again
- add backend config so terraform plans can be completed locally
> fix: add method to increase vault pvc

- cluster/terraform-jx-boot/vault.tf
- has to be added as changing 'pvc' values.
- no string set
> fix: add storageClassName as required. No value.

- cluster/terraform-jx-boot/vault.tf
- tested with a helm template for vault and increasing pvc size
- updating pvc size to 2Gi and chart version
> fix: add pvc.size increase and update chart version

- cluster/terraform-jx-boot/boot.tf
- update jx-git-operator on our forked repo
- this update has been changed upstream (fork is way out of sync)
> feat: update jx-git-operator

- values.auto.tfvars
- upgrade k8s to 1.25.6 and disable spot
> chore: upgrade k8s to 1.25.6

- values.auto.tfvars
> Upgrade/k8s v1.26.6

- values.auto.tfvars
- upgrade k8s 1.27.3 and re-enable SPOT (LAST PR UPGRADE)
> chore: UPGRADE 3: k8s 1.27.3

- values.auto.tfvars
REFERENCE:
fix: increase max ml node to 6 #56
> feat: increase ML NODE max: 6

- cluster/main.tf
- cluster/terraform-jx-registry-acr/main.tf
- cluster/terraform-jx-registry-acr/variables.tf
- cluster/variables.tf
- main.tf
- values.auto.tfvars
- variables.tf
- add acr toggle to disable for future saas clusters
> chore: add an acr toggle for container registry

- cluster/main.tf
- cluster/terraform-jx-boot/health.tf
- cluster/terraform-jx-boot/variables.tf
- cluster/variables.tf
- main.tf
- values.auto.tfvars
- variables.tf
- bring in upstream changes for kuberhealthy toggle
> feat: add install kuberhealthy toggle

- cluster/main.tf
- cluster/terraform-jx-azuredns/main.tf
- cluster/terraform-jx-azuredns/variables.tf
- cluster/variables.tf
- main.tf
- values.auto.tfvars
- variables.tf
- remove precise logic around subdomains and provision when local.enabled is true
> chore: assign a sp regardless of subdomain

- cluster/terraform-jx-azuredns/main.tf
- quick fix as commit message states
> fix: logic on data source as not needed

- cluster/outputs.tf
- cluster/terraform-jx-registry-acr/outputs.tf
- output.tf
- adding output can remove later no biggie
> chore: add output

- cluster/terraform-jx-cluster-aks/cluster/main.tf
- add patch updates to bring in latest security updates for k8s version. This will also refresh the nodes, if a patch is applicable
> feat: add patch automatic updates

- cluster/terraform-jx-registry-acr/main.tf
- fix logic on count for cache rule
> chore: fix the count

- cluster/terraform-jx-cluster-aks/main.tf
> chore: conditionally set rg via data or rg name if created

- cluster/main.tf
- cluster/terraform-jx-cluster-aks/cluster/logging.tf
- cluster/terraform-jx-cluster-aks/cluster/main.tf
- cluster/terraform-jx-cluster-aks/cluster/outputs.tf
- cluster/terraform-jx-cluster-aks/cluster/variables.tf
- cluster/terraform-jx-cluster-aks/main.tf
- cluster/terraform-jx-cluster-aks/variables.tf
- cluster/terraform-jx-cluster-aks/vnet/main.tf
- cluster/variables.tf
- main.tf
- values.auto.tfvars
- variables.tf
- fix azureRM v4.0.0 deprications
- fix toggles for resources that shouldn't be re-provisioned when using modules for multi env
- add orchestrator_version. I have added an ignore changes. However, because we are auto updating the different channels the orch version will change. So good to manage for future mitigation on the nodes. (This wasn't a problem with upstream but more due to my automatic changes).
> chore: fix

- cluster/terraform-jx-cluster-aks/cluster/main.tf
- additional fixes due to new deprecations
> fix: image cleaner attributes

- cluster/main.tf
- cluster/terraform-jx-azure-storage/main.tf
- cluster/terraform-jx-azure-storage/variables.tf
- cluster/variables.tf
- main.tf
- variables.tf
> test: clean up code

- cluster/terraform-jx-boot/boot.tf
- Increase operator resources
- Upgrade version whilst I'm in here
> chore: increase jx-git-op resources

- cluster/terraform-jx-cluster-aks/cluster/main.tf
- temp name for k8s node pool to migrate workload while changing vm_size specs
> feat: add temp node pool for vm_size upgrades

- cluster/terraform-jx-boot/vault.tf
- Amend how vault pulls its images
> fix: change chart location to OCI

- cluster/terraform-jx-cluster-aks/cluster/main.tf
- cluster/terraform-jx-cluster-aks/cluster/variables.tf
- cluster/terraform-jx-cluster-aks/local.tf
- cluster/terraform-jx-cluster-aks/main.tf
- variables.tf
Changes in this PR:
- removal of data source defender log analytics workspace. This was due to production using this as a shared log analytics workspace. Now, it will create its own for more precise logging for the future.
- removal of redundant local condition as will not be used due to the resource passing in log workspace id to the cluster module.
> fix: amend defender data sources and resources

- cluster/main.tf
- cluster/terraform-jx-cluster-aks/cluster/main.tf
- cluster/terraform-jx-cluster-aks/cluster/variables.tf
- cluster/terraform-jx-cluster-aks/main.tf
- cluster/terraform-jx-cluster-aks/variables.tf
- cluster/variables.tf
- main.tf
- values.auto.tfvars
- variables.tf
This reverts commit f80ced94b47ba94103d82e636768389cf5cb6f9f.
> fix: revert cost analysis flags

- cluster/main.tf
- cluster/terraform-jx-cluster-aks/cluster/main.tf
- cluster/terraform-jx-cluster-aks/cluster/variables.tf
- cluster/terraform-jx-cluster-aks/main.tf
- cluster/terraform-jx-cluster-aks/variables.tf
- cluster/variables.tf
- main.tf
- values.auto.tfvars
- variables.tf
Enable [Terraform Arg for deploying AKS cost analysis](https://registry.terraform.io/providers/hashicorp/azurerm/4.14.0/docs/resources/kubernetes_cluster#argument-reference) for build cluster
> feat: create AKS cost analysis flag

- .lighthouse/jenkins-x/triggers.yaml
- cluster/terraform-jx-boot/main.tf
> chore: test helm fix

- cluster/terraform-jx-azurekeyvault/main.tf
Soft delete retention is already set to 90 so cannot be changed.. Reverting change
> chore: soft delete retention

- cluster/main.tf
- cluster/terraform-jx-cluster-aks/cluster/main.tf
- cluster/terraform-jx-cluster-aks/cluster/variables.tf
- cluster/terraform-jx-cluster-aks/main.tf
- cluster/terraform-jx-cluster-aks/variables.tf
- cluster/variables.tf
- main.tf
- values.auto.tfvars
- variables.tf
Add LLM node pool for internal Open WebUI / Ollama functionality
> commit: build llm node pool

- cluster/terraform-jx-cluster-aks/cluster/main.tf
- cluster/terraform-jx-registry-acr/main.tf
Enable premium tier for container registry, as it's cheaper than standard at current usage (~1.6TB):
**Standard Tier Cost**
**Premium Tier Cost**
Also offers significant bandwidth and Read/Write Ops upgrades - https://learn.microsoft.com/en-us/azure/container-registry/container-registry-skus#service-tier-features-and-limits, so worth any marginal cost increases.
> chore: Upgrade ACR to premium tier

- cluster/terraform-jx-cluster-aks/cluster/main.tf
- values.auto.tfvars
Testing with new VM type of Standard_NC40ads_H100_v5
> chore: build llm node pool

- cluster/terraform-jx-cluster-aks/cluster/main.tf
Comment out llm node pool until we get response from Azure on quotas
> chore: remove llm node pool

- cluster/terraform-jx-cluster-aks/cluster/main.tf
Rebuild LLM node pool with correct label for nodeSelector
> chore: add node pool with llm node label

- cluster/terraform-jx-cluster-aks/cluster/main.tf
> chore: create llm node pool with additional taint

- values.auto.tfvars
Increase max LLM node count to 2
> chore: increase max node count llm

- values.auto.tfvars
Allow llm node pool to scale to zero
> chore: set llm node minimum to zero
